/* this file is automatically generated by build script (see SConstruct), do not edit */
#include "version.hpp"

std::string software_build()
{
	return std::string{"20180726.5fad8fa"};
}

std::string software_version()
{
	return std::string{"0.2.0"};
}

