FROM ubuntu:18.04

# Install build dependencies
RUN apt-get update && apt-get install -y \
	pkg-config \
	scons \
	git \
	g++ \
	libgstreamer1.0-dev \
	libzmq3-dev \
	libasound2-dev \
	libboost-all-dev \
	python3-zmq \
	&& rm -rf /var/lib/apt/lists/*

# Work directory inside container
WORKDIR /src

CMD ["/bin/bash"]
