name: rplay
base: core18
version: '0.5+git'
summary: remote player server
description: |
  Remote player server protocol implementation, see [spec.txt](https://github.com/sansajn/remoteplayer/blob/master/docs/spec.txt).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  rplay:
    command: ../parts/rplay

parts:
  rplay:
    source: https://github.com/sansajn/remoteplayer.git
    source-subdir: rplay/
    plugin: scons
    
    build-packages:
    - pkg-config
    - scons
    - git
    - g++
    - libgstreamer1.0-dev
    - libzmq3-dev
    - libasound2-dev
    - libboost-all-dev
    
    stage-packages: 
    - libgstreamer1.0-0
    - libzmq5
    - libasound2
    - libboost-filesystem1.65.1
    - libboost-thread1.65.1
    - libboost-log1.65.1
    - libboost-date-time1.65.1
    - libboost-program-options1.65.1
